### PR TITLE
Rudolf Disappear Skill Fix

### PR DESCRIPTION
**Pull request by bobbyng626**
Disappear Skill Fix
Fixed TU timer for appearing and disappearing of character and shadow

### CODE REVIEW

**Comment by tyt2y3** [comment]
What is the `get_living_object` method for?

**Comment by bobbyng626** [comment]
get_living_object is for AI application, in the LF_19 repo. It is for helping the AI to find out the existing living object so to handle with 'Disappear' Skill of Rudolf. However, I did not commit any changes to LF_19, the AI files, so you cannot see any application of the function.

**Comment by bobbyng626** [comment]
#19 These changes should make Rudolf invisible and become super state in a certain time interval

**Comment by bobbyng626** [comment]
#36 explained the final change on the 'disappear skill' due to complicated conflicts between branches

**Pull request closed without merging**
