### PR TITLE
Implement Rudolf's transform

### PR DESCRIPTION
**Pull request by juinc**

### CODE REVIEW

**Comment by tyt2y3** [comment]
Hi Juin, glad to see you here. To be honest I am so surprised so have received a pull request! Thank you so much.
And btw, why did you close the PR? Do you think it is not yet ready for merging?

**Comment by juinc** [comment]
Hi Chris, nice to meet you! I found this project 2 weeks ago and I am totally amazed! This PR is not completed yet. I am trying to implement the rest of the classic characters that the project does not support (Julian, LouisEX, etc)

**Comment by tyt2y3** [comment]
Great! Your WIP seems very promising. Thank you for the great work! If you have any confusion, we should discuss. (I dont think I could remember too much details now though).

**Comment by tyt2y3** [comment]
I also have added Henry and Rudolf in the content pack [LF2_19](https://github.com/Project-F/LF2_19). I will add more as you need them!

**Comment by juinc** [comment]
Appreciate it 👍 Actually I found all the data and resource from [here](https://github.com/06wj/lf2/tree/master/src/res) and capable to use your tool to covert them ;) Good work btw.

**Comment by tyt2y3** [comment]
How are you doing lately @ccniuj ?

**Pull request closed without merging**
